# Re-trigger CI
name: CI Pipeline Jakebot

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        # Escolha a versão do Python usada no seu projeto
        python-version: '3.10' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Verifique se o arquivo requirements.txt está na raiz ou em backend/
        # Ajuste o caminho se necessário: pip install -r backend/requirements.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # Se não houver requirements.txt, considere gerar um com 'pip freeze > requirements.txt' no seu ambiente local
        # e adicioná-lo ao repositório.

    - name: Lint with flake8
      run: |
       pip install flake8
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=venv
        # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=venv

    # Descomente e ajuste esta seção se você tiver testes automatizados
    # - name: Run Tests
    #   run: |
    #     # Se for Django: python manage.py test
    #     # Se for pytest: pytest
    #     echo "Nenhum passo de teste configurado ainda."

    - name: Run Bot Script
      run: |
        # Execute o script principal passando o caminho do CSV como argumento
        python backend/bots/ler_csv.py backend/bots/assets/Comentários_por_ID.json